options:
  formatter: stylish

files:
  include: '**/*.scss'

rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-color-keywords: 0
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 0
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-zero: 1
  no-transition-all: 1
  no-url-protocols: 1
  no-vendor-prefixes: 1
  no-warn: 1

  # Nesting
  force-attribute-nesting: 1
  force-element-nesting: 0
  force-pseudo-nesting: 1

  # Name Formats
  function-name-format: 1
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 0

  # Style Guide
  border-zero:
    - 1
    -
      convention: 'none'
  brace-style: 1
  clean-import-paths: 1
  empty-args: 1
  hex-length: 1
  hex-notation: 1
  indentation: 1
  leading-zero:
    - 1
    - include: true
  nesting-depth: 0
  property-sort-order:
    - 1
    -
      order:
        - content
        - display
        - position
        - top
        - left
        - right
        - bottom
        -
        - flex
        - flex-basis
        - flex-direction
        - flex-flow
        - flex-grow
        - flex-shrink
        - flex-wrap
        - align-content
        - align-items
        - align-self
        - justify-content
        - order
        -
        - float
        - clear
        -
        - margin
        - margin-top
        - margin-left
        - margin-right
        - margin-bottom
        -
        - padding
        - padding-top
        - padding-left
        - padding-right
        - padding-bottom
        -
        - width
        - min-width
        - max-width
        -
        - height
        - min-height
        - max-height
        -
        - overflow
        - z-index
        -
        - columns
        - column-gap
        - column-fill
        - column-rule
        - column-span
        - column-count
        - column-width
        -
        - color
        -
        - background
        - background-color
        - background-image
        - background-repeat
        - background-position
        - background-size
        -
        - # Border
        -
        - border
        - border-top
        - border-right
        - border-bottom
        - border-left
        - border-width
        - border-top-width
        - border-left-width
        - border-right-width
        - border-bottom-width
        -
        - border-collapse
        - border-spacing
        - border-style
        - border-top-style
        - border-left-style
        - border-right-style
        - border-bottom-style
        -
        - border-radius
        - border-top-left-radius
        - border-top-right-radius
        - border-bottom-left-radius
        - border-bottom-right-radius
        -
        - border-color
        - border-top-color
        - border-left-color
        - border-right-color
        - border-bottom-color
        -
        - outline
        - outline-color
        - outline-offset
        - outline-style
        - outline-width
        -
        - box-shadow
        -
        - # Text
        -
        - font
        - font-family
        - font-size
        - font-smoothing
        - font-style
        - font-variant
        - font-weight
        -
        - letter-spacing
        - line-height
        - list-style
        -
        - text-align
        - text-decoration
        - text-indent
        - text-overflow
        - text-rendering
        - text-shadow
        - text-transform
        - text-wrap
        -
        - white-space
        - word-spacing
        -
        - # Other
        -
        - caption-side
        - cursor
        - empty-cells
        - opacity
        - quotes
        - speak
        - table-layout
        - vertical-align
        - visibility
        -
        - animation
        - transform
        - transition
  quotes: 1
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
